#!/usr/bin/env python3
"""
Generate precomputed Lambert W0 lookup table for FP127.

Computes W(2^k) for k=0..6 (i.e., W(1), W(2), W(4), ..., W(64)) 
in 127.128 fixed-point format for use as initial guesses.

Output: Huff #define constant lines for inclusion in constants.huff
"""

import mpmath
mpmath.mp.dps = 80  # 80 decimal digits for intermediate calculations

def to_fp127_hex(value):
    """Convert a decimal value to 127.128 fixed-point hex string."""
    # FP127 format: value * 2^128
    fp127_int = int(value * (2**128))
    # Handle negative values (two's complement)
    if fp127_int < 0:
        fp127_int = (1 << 256) + fp127_int
    return f"0x{fp127_int:064x}"

def generate_lambertw0_table():
    """Generate W(1) through W(64) for dense LUT."""
    print("// ============================================================================")
    print("// Lambert W0 Lookup Table")
    print("// ============================================================================")
    print("// Precomputed W(x) values for x=1..64 in 127.128 format")
    print("// Dense table for linear interpolation in FP127_LAMBERT_W0()")
    print("// Generated by scripts/fp127/generators/generate_lambertw0_table.py")
    print()
    
    for x in range(1, 65):
        w = mpmath.lambertw(x, k=0)  # Principal branch
        w_float = float(w)
        fp127_hex = to_fp127_hex(w)
        
        # Generate constant name
        const_name = f"LAMBERTW0_W{x}"
        
        print(f"// W({x}) ≈ {w_float:.18f}")
        print(f"#define constant {const_name} = {fp127_hex}")
        print()

def verify_values():
    """Verify the computed values for sanity check."""
    print("\n// Verification:")
    print("// W(1) ≈ 0.5671432904097838")
    print("// W(e) ≈ 1.0 (exact)")
    print("// W(8) ≈ 1.5972779327463210")
    print("// W(16) ≈ 2.0305431848688176")
    print()
    
    # Verify W(e) = 1 as a sanity check
    e = mpmath.e
    w_e = mpmath.lambertw(e, k=0)
    print(f"// Sanity check: W(e) = {float(w_e):.18f} (should be ~1.0)")
    
    # Check monotonicity
    print("\n// Monotonicity check (W is strictly increasing):")
    for x in range(1, 16):
        w1 = float(mpmath.lambertw(x, k=0))
        w2 = float(mpmath.lambertw(x+1, k=0))
        print(f"// W({x}) < W({x+1}): {w1:.6f} < {w2:.6f} = {w1 < w2}")

if __name__ == "__main__":
    generate_lambertw0_table()
    verify_values()
