#!/usr/bin/env python3
"""
Generate LOG2 range-reduction constants for log2.huff.

The range reduction uses 7 stages to reduce m from [1,2) to [1, 2^(1/128)):
- Stage k tests if m >= 2^(1/2^k)
- If yes: multiply by 2^(-1/2^k) and add 2^(-k) to fractional accumulator

Constants needed:
- LOG2_RT2 through LOG2_RT7: thresholds 2^(1/2^k) for k=2..7
- LOG2_INV_RT1 through LOG2_INV_RT7: multipliers 2^(-1/2^k) for k=1..7
- Note: LOG2_RT1 = sqrt(2) is already defined as SQRT2_FP127
"""

from mpmath import mp, mpf, power

mp.dps = 200
FP127_SCALE = mpf(2) ** 128
TWO = mpf(2)

def to_fp127_hex(value):
    """Convert a positive real value to 64-char hex (FP127 = value * 2^128)."""
    scaled = int(value * FP127_SCALE)
    if scaled < 0:
        scaled = (1 << 256) + scaled
    return f"0x{scaled:064x}"

def main():
    print("// ============================================================================")
    print("// LOG2 Range-Reduction Constants")
    print("// ============================================================================")
    print("// Thresholds and multipliers for 7-stage range reduction")
    print("// Generated by scripts/generators/generate_log2_range_constants.py")
    print()
    
    # Stage 1: k=1, threshold = 2^(1/2) = sqrt(2), multiplier = 2^(-1/2) = 1/sqrt(2)
    # SQRT2_FP127 is defined separately, but we need INV_RT1
    inv_rt1 = power(TWO, mpf(-1)/mpf(2))
    print(f"// Stage 1: threshold = sqrt(2) (use SQRT2_FP127), multiplier = 1/sqrt(2)")
    print(f"#define constant LOG2_INV_RT1 = {to_fp127_hex(inv_rt1)}")
    print()
    
    # Stages 2-7: k=2..7
    for k in range(2, 8):
        exponent = mpf(1) / mpf(2**k)
        threshold = power(TWO, exponent)
        multiplier = power(TWO, -exponent)
        
        print(f"// Stage {k}: threshold = 2^(1/{2**k}), multiplier = 2^(-1/{2**k})")
        print(f"#define constant LOG2_RT{k} = {to_fp127_hex(threshold)}")
        print(f"#define constant LOG2_INV_RT{k} = {to_fp127_hex(multiplier)}")
        print()
    
    print("// ============================================================================")
    print("// Summary")
    print("// ============================================================================")
    print("// Total: 7 thresholds (RT2-RT7) + 7 multipliers (INV_RT1-INV_RT7)")
    print("// Note: SQRT2_FP127 serves as LOG2_RT1 (threshold for stage 1)")

if __name__ == "__main__":
    main()
