#!/usr/bin/env python3
"""
Generate precomputed Lambert W0 lookup table for FP128.

Computes W(2^k) for k=0..6 (i.e., W(1), W(2), W(4), ..., W(64)) 
in 128.128 fixed-point format for use as initial guesses.

Output: Huff #define constant lines for inclusion in constants.huff
"""

import mpmath
mpmath.mp.dps = 80  # 80 decimal digits for intermediate calculations

def to_fp128_hex(value):
    """Convert a decimal value to 128.128 fixed-point hex string."""
    # FP128 format: value * 2^128
    fp128_int = int(value * (2**128))
    # Handle negative values (two's complement)
    if fp128_int < 0:
        fp128_int = (1 << 256) + fp128_int
    return f"0x{fp128_int:064x}"

def generate_lambertw0_table():
    """Generate W(2^k) for k=0..6."""
    print("// ============================================================================")
    print("// Lambert W0 Lookup Table")
    print("// ============================================================================")
    print("// Precomputed W(2^k) values for k=0..6 in 128.128 format")
    print("// Used for fast initial guesses in FP128_LAMBERT_W0()")
    print("// Generated by scripts/generators/generate_lambertw0_table.py")
    print()
    
    for k in range(7):
        x = 2**k
        w = mpmath.lambertw(x, k=0)  # Principal branch
        w_float = float(w)
        fp128_hex = to_fp128_hex(w)
        
        # Generate constant name
        const_name = f"LAMBERTW0_W{x}"
        
        print(f"// W({x}) ≈ {w_float:.18f}")
        print(f"#define constant {const_name} = {fp128_hex}")
        print()

def verify_values():
    """Verify the computed values for sanity check."""
    print("\n// Verification:")
    print("// W(1) ≈ 0.5671432904097838")
    print("// W(2) ≈ 0.8526055020137255")
    print("// W(4) ≈ 1.2021678710577608")
    print("// W(8) ≈ 1.5972779327463210")
    print("// W(16) ≈ 2.0305431848688176")
    print("// W(32) ≈ 2.4959503708256665")
    print("// W(64) ≈ 2.9881634531780684")
    print()
    
    # Verify W(e) = 1 as a sanity check
    e = mpmath.e
    w_e = mpmath.lambertw(e, k=0)
    print(f"// Sanity check: W(e) = {float(w_e):.18f} (should be ~1.0)")

if __name__ == "__main__":
    generate_lambertw0_table()
    verify_values()
