#!/usr/bin/env python3
"""
Generate bit-level lookup tables for 128.128 fixed-point transcendentals.

Binary digit-by-digit method: instead of decimal digits (11x10 table),
we decompose the exponent bit-by-bit. For exp(x), if x = sum of 2^k bits,
then exp(x) = product of exp(2^k) for each set bit.

Table entries:
  EXP_BIT_TABLE[k] = e^(2^(k - FRAC_OFFSET))  in FP127 format

where FRAC_OFFSET centers the table so that k=0 corresponds to the smallest
fractional bit we care about, and the table covers both integer and fractional
bit positions.

For exp: useful input range is roughly [-88, 88], so we need ~7 integer bits.
We store entries for bit positions covering 2^(-128) up to 2^6 (= 64).
That's 135 entries, each 32 bytes = 4,320 bytes of bytecode.

Output: Huff #define table declarations with raw 32-byte FP127 words.
"""

from mpmath import mp, mpf, power, log, exp as mp_exp, sqrt as mp_sqrt
from mpmath import sin as mp_sin, cos as mp_cos, tanh as mp_tanh, atan as mp_atan
from mpmath import pi as mp_pi
import sys
import os

mp.dps = 80

FP127_SCALE = mpf(2) ** 128
TWO = mpf(2)


def to_fp127_hex(value):
    """Convert a positive real value to 64-char hex (FP127 = value * 2^128)."""
    scaled = int(value * FP127_SCALE)
    if scaled < 0:
        scaled = (1 << 256) + scaled
    return f"0x{scaled:064x}"


def generate_bkm_table():
    """
    Generate BKM_LN_TABLE: entry k = ln(1 + 2^-k) for k = 0..127.

    This single table serves both exp and ln via the BKM algorithm:
    - exp: multiply acc by (1 + 2^-k) using acc += acc >> k
    - ln:  build up product from 1 toward x using acc += acc >> k

    k=0:   ln(1 + 2^0)   = ln(2) ≈ 0.6931
    k=1:   ln(1 + 2^-1)  = ln(1.5) ≈ 0.4055
    k=2:   ln(1 + 2^-2)  = ln(1.25) ≈ 0.2231
    ...
    k=127: ln(1 + 2^-127) ≈ 2^-127 (tiny, approximately equal to 2^-127)
    
    Note: Entries k=128..134 are below FP127 precision and have been trimmed.
    """
    entries = []
    for k in range(128):
        # ln(1 + 2^-k)
        val = log(mpf(1) + TWO ** (-k))
        entries.append(to_fp127_hex(val))
    return entries


def format_table(name, entries, comment):
    """Format entries as a Huff code table."""
    lines = []
    lines.append(f"/// @notice {comment}")
    lines.append(f"/// @dev {len(entries)} entries x 32 bytes = {len(entries) * 32} bytes")
    lines.append(f"///      Entry k (byte offset k*32): ln(1 + 2^-k)")
    lines.append(f"///      k=0 -> ln(2), k=1 -> ln(1.5), ..., k=127 -> ln(1 + 2^-127)")
    lines.append(f"#define table {name} {{")
    for i, entry in enumerate(entries):
        if i == 0:
            label = "ln(2)"
        elif i == 1:
            label = "ln(1.5)"
        elif i <= 10:
            label = f"ln(1 + 2^-{i})"
        else:
            label = f"ln(1 + 2^-{i})"
        lines.append(f"    {entry}  // k={i}: {label}")
    lines.append("}")
    return "\n".join(lines)


def generate_constants():
    """Generate companion constants for the BKM algorithm."""
    lines = []
    lines.append("/// @notice Constants for BKM transcendental functions")
    lines.append("")

    # Number of table entries
    lines.append("// BKM_TABLE_SIZE: number of entries in BKM_LN_TABLE")
    lines.append("#define constant BKM_TABLE_SIZE = 0x80  // 128")
    lines.append("")

    # Max table index (127 = k for ln(1 + 2^-127))
    lines.append("// BKM_MAX_K: highest k index in table (127)")
    lines.append("#define constant BKM_MAX_K = 0x7F  // 127")
    lines.append("")

    # For reference
    ln2 = log(2)
    lines.append(f"// LN2_FP127: ln(2) = BKM_LN_TABLE[0] (already defined in constants.huff)")
    lines.append(f"// Value: {ln2}")
    lines.append("")

    return "\n".join(lines)


def main():
    print("/// @title FP127 BKM Lookup Table for Transcendental Functions")
    print("/// @notice BKM algorithm table for exp and ln (shift-add method)")
    print("/// @dev Generated by scripts/generate_fp127_tables.py")
    print("/// @dev Each entry is a 32-byte FP127 value (128.128 format)")
    print("///")
    print("/// BKM Algorithm (exp):")
    print("///   exp(x) where x is FP127, x >= 0:")
    print("///   acc = ONE_FP127, rem = x")
    print("///   for k = 0 to 134:")
    print("///       if rem >= BKM_LN_TABLE[k]:")
    print("///           acc = acc + (acc >> k)   // multiply by (1 + 2^-k)")
    print("///           rem = rem - BKM_LN_TABLE[k]")
    print("///   return acc")
    print("///")
    print("/// BKM Algorithm (ln):")
    print("///   ln(x) where x is FP127, x >= 1:")
    print("///   result = 0, acc = ONE_FP127")
    print("///   for k = 0 to 134:")
    print("///       trial = acc + (acc >> k)   // multiply by (1 + 2^-k)")
    print("///       if trial <= x:")
    print("///           acc = trial")
    print("///           result = result + BKM_LN_TABLE[k]")
    print("///   return result")
    print("")

    # Constants
    print(generate_constants())
    print("")

    # BKM table
    print("// ============================================================================", file=sys.stderr)
    print("// Generating BKM_LN_TABLE (128 entries)...", file=sys.stderr)
    bkm_entries = generate_bkm_table()
    print(format_table("BKM_LN_TABLE", bkm_entries, "ln(1 + 2^-k) for k=0..127 (BKM algorithm)"))
    print("")

    # Verification
    print("// ============================================================================", file=sys.stderr)
    print("// Verification:", file=sys.stderr)

    # Check a few values
    ln2 = log(2)
    print(f"//   ln(2) = ln(1 + 2^0) = {ln2}", file=sys.stderr)
    print(f"//   BKM_LN_TABLE[0] = {bkm_entries[0]}", file=sys.stderr)
    print(f"//   Expected FP127 hex: {to_fp127_hex(ln2)}", file=sys.stderr)

    ln1_5 = log(mpf(1.5))
    print(f"//   ln(1.5) = ln(1 + 2^-1) = {ln1_5}", file=sys.stderr)
    print(f"//   BKM_LN_TABLE[1] = {bkm_entries[1]}", file=sys.stderr)

    ln1_25 = log(mpf(1.25))
    print(f"//   ln(1.25) = ln(1 + 2^-2) = {ln1_25}", file=sys.stderr)
    print(f"//   BKM_LN_TABLE[2] = {bkm_entries[2]}", file=sys.stderr)

    # Sum of all L[k] gives us the max range
    sum_all = sum(log(mpf(1) + TWO**(-k)) for k in range(128))
    print(f"//   Sum of all L[k] = {sum_all}", file=sys.stderr)
    print(f"//   This covers exp range up to e^{sum_all} = {mp_exp(sum_all)}", file=sys.stderr)

    # Total size
    total_bytes = len(bkm_entries) * 32
    print(f"//", file=sys.stderr)
    print(f"//   Total table size: {total_bytes} bytes ({total_bytes/1024:.1f} KB)", file=sys.stderr)
    print(f"//   Contract size limit: 24,576 bytes (24 KB)", file=sys.stderr)
    print(f"//   Tables use {total_bytes/24576*100:.1f}% of limit", file=sys.stderr)
    print(f"//   Savings: 224 bytes (trimmed 7 zero entries)", file=sys.stderr)


if __name__ == "__main__":
    main()
