#!/usr/bin/env python3
"""
Generate EXP2 lookup table constants for 128.128 fixed-point exponential.

For ABDK-style exp2 computation:
  2^x where x has fractional bits b1, b2, ..., b128
  2^x = 2^(b1*2^-1 + b2*2^-2 + ... + b128*2^-128)
      = product of 2^(2^-k) for each set bit k

Each constant EXP2_Kn = 2^(2^(-n)) in 1.128 format (33 hex chars without leading zeros).
In full 128.128 format with the integer part, it's 129 bits minimum.

Since 2^(2^(-1)) = sqrt(2) ≈ 1.414, and 2^(2^(-128)) ≈ 1 + 2^(-128)*ln(2),
the integer part is always 1 (values are in range [1, sqrt(2)]).

Format: Each constant is stored as value * 2^128 (128.128 fixed-point).
"""

from mpmath import mp, mpf, power, log, log as mp_log

# Set precision to 200 decimal digits for accurate coefficient computation
mp.dps = 200

# 128.128 fixed-point scale factor
FP127_SCALE = mpf(2) ** 128
TWO = mpf(2)


def to_fp127_hex(value):
    """Convert a positive real value to 64-char hex (FP127 = value * 2^128)."""
    scaled = int(value * FP127_SCALE)
    if scaled < 0:
        scaled = (1 << 256) + scaled
    return f"0x{scaled:064x}"


def generate_exp2_constants():
    """
    Generate EXP2_K constants: 2^(2^(-k)) for k=1..128.
    
    k=1:  2^(2^-1)   = 2^0.5    = sqrt(2)     ≈ 1.41421356...
    k=2:  2^(2^-2)   = 2^0.25   = sqrt(sqrt(2)) ≈ 1.18920712...
    k=3:  2^(2^-3)   = 2^0.125  ≈ 1.09050773...
    ...
    k=64: 2^(2^-64)  ≈ 1 + 2^-64 * ln(2)
    ...
    k=128: 2^(2^-128) ≈ 1 + 2^-128 * ln(2)
    
    For large k, 2^(2^-k) ≈ 1 + 2^-k * ln(2) (first-order Taylor).
    """
    constants = []
    for k in range(1, 129):  # k=1 to k=128
        # 2^(2^(-k))
        exponent = TWO ** (-k)
        val = power(TWO, exponent)
        hex_val = to_fp127_hex(val)
        constants.append((k, val, hex_val))
    return constants


def verify_against_abdk():
    """
    Verify our constants against ABDK's first 64.
    ABDK uses 1.128 format (no leading zero bytes for integer part).
    
    ABDK k=1 (bit 63 in their code): 0x16A09E667F3BCC908B2FB1366EA957D3E
    This is sqrt(2) in 1.128 format = sqrt(2) * 2^128.
    
    Let's verify:
    sqrt(2) = 1.41421356237309504880168872420969807856967187537694...
    sqrt(2) * 2^128 = 0x16A09E667F3BCC908B2FB1366EA957D3E (129 bits)
    
    Our format: we store in 128.128, so same value but with leading zeros
    to pad to 64 hex chars (256 bits).
    """
    abdk_k1 = 0x16A09E667F3BCC908B2FB1366EA957D3E
    our_sqrt2 = power(TWO, TWO**(-1))  # = sqrt(2)
    our_scaled = int(our_sqrt2 * FP127_SCALE)
    
    print(f"// Verification against ABDK:", file=__import__('sys').stderr)
    print(f"//   ABDK k=1 (sqrt(2) in 1.128): 0x{abdk_k1:033x}", file=__import__('sys').stderr)
    print(f"//   Our k=1 (sqrt(2) * 2^128):   0x{our_scaled:064x}", file=__import__('sys').stderr)
    
    # Extract last 33 hex chars (129 bits) from our value to compare
    our_trimmed = our_scaled & ((1 << 129) - 1)
    print(f"//   Our k=1 trimmed to 129 bits: 0x{our_trimmed:033x}", file=__import__('sys').stderr)
    
    if our_trimmed == abdk_k1:
        print(f"//   MATCH! Our constant matches ABDK exactly.", file=__import__('sys').stderr)
    else:
        diff = abs(our_trimmed - abdk_k1)
        print(f"//   DIFFERS by {diff} ({diff.bit_length()} bits)", file=__import__('sys').stderr)
    
    return our_scaled == our_trimmed  # True if no leading bits beyond 129


def main():
    import sys
    
    print("/// @title FP127 EXP2 Constants for ABDK-style Exponentiation")
    print("/// @notice 2^(2^(-k)) constants for k=1..128 in 128.128 format")
    print("/// @dev Generated by scripts/generate_exp2_constants.py")
    print("/// @dev Each constant is 2^(2^(-k)) * 2^128 (128.128 fixed-point)")
    print("///")
    print("/// Algorithm for exp2(x) where x is 128.128:")
    print("///   Split x into integer k_int and fractional frac parts")
    print("///   result = ONE_FP127 (in 1.128 internal format)")
    print("///   for i = 1 to 128:")
    print("///     if bit (128-i) of frac is set:")
    print("///       result = (result * EXP2_Ki) >> 128")
    print("///   result = result << k_int (or >> -k_int if negative)")
    print("///")
    print("/// For exp(x):")
    print("///   exp(x) = exp2(x * INV_LN2)")
    print("")
    
    # Verify against ABDK
    verify_against_abdk()
    print("", file=sys.stderr)
    
    # Generate constants
    print("// ============================================================================")
    print("// EXP2 Constants: 2^(2^(-k)) for k=1..128")
    print("// ============================================================================")
    print("")
    
    constants = generate_exp2_constants()
    
    for k, val, hex_val in constants:
        # Add helpful comment for first few and key values
        if k <= 8:
            exponent = TWO ** (-k)
            print(f"// EXP2_K{k}: 2^(2^-{k}) = 2^{float(exponent):.10g} ≈ {float(val):.15g}")
        elif k == 64:
            print(f"// EXP2_K{k}: 2^(2^-{k}) ≈ 1 + 2^-{k}*ln(2)")
        elif k == 128:
            print(f"// EXP2_K{k}: 2^(2^-{k}) ≈ 1 + tiny (below precision threshold)")
        
        print(f"#define constant EXP2_K{k} = {hex_val}")
        
        if k in [8, 32, 64, 96]:
            print("")  # Add spacing at intervals
    
    print("")
    
    # Print summary
    print("// ============================================================================", file=sys.stderr)
    print("// Summary:", file=sys.stderr)
    print(f"//   Generated {len(constants)} constants (EXP2_K1 through EXP2_K128)", file=sys.stderr)
    print(f"//   Each constant: 64 hex chars (256 bits in 128.128 format)", file=sys.stderr)
    print(f"//   Total bytecode size: {len(constants) * 32} bytes", file=sys.stderr)
    
    # Verify range
    sqrt2 = power(TWO, mpf(0.5))
    print(f"//   EXP2_K1 = sqrt(2) ≈ {float(sqrt2):.15g}", file=sys.stderr)
    print(f"//   EXP2_K128 ≈ 1 + 2^-128*ln(2) ≈ 1.0000000000000000000000000000000000000020", file=sys.stderr)


if __name__ == "__main__":
    main()
