#!/usr/bin/env python3
"""
Generate and verify LOG2_H constants for the hybrid log2 algorithm.

The algorithm computes log2(1+f) = f * INV_LN2 * h(f) where h(f) = ln(1+f)/f.
The function h(f) has exact Taylor coefficients: h_n = (-1)^n / (n+1).

This script:
1. Generates the FP128 hex constants for h(f) coefficients
2. Simulates the full algorithm in FP128 arithmetic
3. Verifies precision over many test points
"""

import mpmath
mpmath.mp.dps = 150  # 150 decimal digits for intermediate calculations

def to_fp128_hex(value):
    """Convert a decimal value to FP128 hex string (128.128 fixed-point)."""
    scaled = value * mpmath.mpf(2)**128
    int_val = int(mpmath.nint(scaled))
    if int_val < 0:
        int_val = (1 << 256) + int_val
    return f"0x{int_val:064x}"

def to_fp128_int(value):
    """Convert a decimal value to FP128 integer representation."""
    scaled = value * mpmath.mpf(2)**128
    int_val = int(mpmath.nint(scaled))
    if int_val < 0:
        int_val = (1 << 256) + int_val
    return int_val

def from_fp128(val):
    """Convert FP128 integer to decimal."""
    if val >= (1 << 255):
        val -= (1 << 256)
    return mpmath.mpf(val) / mpmath.mpf(2)**128

def fp128_mul_sim(a, b):
    """Simulate FP128_MUL: full 512-bit product, take upper 256 bits."""
    # Handle signs
    a_signed = a if a < (1 << 255) else a - (1 << 256)
    b_signed = b if b < (1 << 255) else b - (1 << 256)
    product = a_signed * b_signed
    result = product >> 128
    if result < 0:
        result = (1 << 256) + result
    return result & ((1 << 256) - 1)

def fp128_square_sim(a):
    """Simulate FP128_SQUARE."""
    return fp128_mul_sim(a, a)

def fp128_add(a, b):
    """Simulate FP128 addition."""
    return (a + b) & ((1 << 256) - 1)

def fp128_sub(a, b):
    """Simulate FP128 subtraction (a - b)."""
    return (a - b) & ((1 << 256) - 1)

def main():
    print("=" * 70)
    print("LOG2_H Constants for Hybrid log2 Algorithm")
    print("=" * 70)
    print()
    print("h(f) = ln(1+f)/f = sum_{n=0}^{inf} (-1)^n / (n+1) * f^n")
    print("     = 1 - f/2 + f^2/3 - f^3/4 + ...")
    print()
    
    # Generate coefficients
    N_PRE = 7   # Number of squaring pre-iterations
    DEGREE = 17  # Polynomial degree
    
    coeffs_mpf = [mpmath.mpf((-1)**n) / (n + 1) for n in range(DEGREE + 1)]
    coeffs_fp128 = [to_fp128_int(c) for c in coeffs_mpf]
    
    # Constants
    ONE_FP128 = 1 << 128
    TWO_FP128 = 2 << 128
    INV_LN2 = to_fp128_int(1 / mpmath.log(2))
    
    print("=" * 70)
    print("Huff constants (copy to constants.huff):")
    print("=" * 70)
    print()
    print("// ============================================================================")
    print("// LOG2 Hybrid Algorithm: h(f) = ln(1+f)/f Polynomial Coefficients")
    print("// ============================================================================")
    print(f"// Degree-{DEGREE} polynomial for h(f) = ln(1+f)/f")
    print("// Coefficients: h_n = (-1)^n / (n+1)")
    print("// Generated by scripts/generate_log2_rational.py")
    print("// Evaluate via Horner: h(f) = H0 + f*(H1 + f*(H2 + ... + f*H_n))")
    print("// Then: log2(1+f) = f * INV_LN2 * h(f)")
    print("// Note: LOG2_H0 = ONE_FP128 (use [ONE_FP128] directly)")
    print()
    
    for n in range(1, DEGREE + 1):
        hex_val = to_fp128_hex(coeffs_mpf[n])
        sign_str = "+" if coeffs_mpf[n] > 0 else ""
        frac_str = f"1/{n+1}" if n % 2 == 0 else f"-1/{n+1}"
        print(f"#define constant LOG2_H{n} = {hex_val}  // {frac_str}")
    
    print()
    print(f"// Total: {DEGREE} coefficients (H1..H{DEGREE}), H0 = ONE_FP128")
    
    # Simulate full algorithm
    print()
    print("=" * 70)
    print("Precision Verification")
    print("=" * 70)
    print()
    
    # Test on interval [1, 2) after normalization
    # After N_PRE squarings, m is in [1, 2^(1/2^N_PRE))
    width_after_pre = mpmath.power(2, mpmath.mpf(1) / mpmath.power(2, N_PRE)) - 1
    print(f"After {N_PRE} pre-squarings, f in [0, {float(width_after_pre):.6f})")
    print()
    
    worst_err = mpmath.mpf(0)
    worst_f = None
    num_tests = 10000
    
    for i in range(1, num_tests + 1):
        # Test input: m in [1, 2) -> will go through pre-squarings
        # For simulation, test f directly in the post-pre-squaring range
        f_mpf = width_after_pre * i / num_tests
        f_fp128 = to_fp128_int(f_mpf)
        
        # Horner evaluation of h(f) in FP128
        # h(f) = H_n + f*(H_{n-1} + f*(...))
        # Actually Horner from highest to lowest: start with H_n, then *f + H_{n-1}, etc.
        result_fp128 = coeffs_fp128[DEGREE]
        for n in range(DEGREE - 1, -1, -1):
            result_fp128 = fp128_mul_sim(result_fp128, f_fp128)
            result_fp128 = fp128_add(result_fp128, coeffs_fp128[n])
        
        # h_val = result
        # log2(1+f) = f * INV_LN2 * h(f)
        temp = fp128_mul_sim(f_fp128, INV_LN2)
        log2_fp128 = fp128_mul_sim(temp, result_fp128)
        
        log2_result = from_fp128(log2_fp128)
        log2_exact = mpmath.log(1 + f_mpf) / mpmath.log(2)
        
        err = abs(log2_result - log2_exact)
        if err > worst_err:
            worst_err = err
            worst_f = f_mpf
    
    bits = float(-mpmath.log(worst_err, 2)) if worst_err > 0 else 999
    print(f"Tested {num_tests} points in [0, {float(width_after_pre):.6f})")
    print(f"Worst error: 2^-{bits:.1f} bits")
    print(f"Worst point: f = {float(worst_f):.10f}")
    print()
    
    if bits >= 125:
        print("SUCCESS: Precision meets 125+ bit target")
    else:
        print(f"WARNING: Precision ({bits:.1f} bits) below 125-bit target")
    
    # Also test the full algorithm including pre-squarings
    print()
    print("=" * 70)
    print("Full Algorithm Simulation (including pre-squarings)")
    print("=" * 70)
    print()
    
    worst_err = mpmath.mpf(0)
    worst_x = None
    
    for i in range(1, num_tests + 1):
        # x in [1.001, 2) -- avoid x=1 (log2=0)
        x_mpf = mpmath.mpf('1.001') + (mpmath.mpf('0.998') * i / num_tests)
        x_fp128 = to_fp128_int(x_mpf)
        
        # Already normalized to [1, 2), so m = x
        m = x_fp128
        frac_top = 0  # Will accumulate top 7 fractional bits
        
        # 7 pre-squarings
        for bit_pos in range(127, 127 - N_PRE, -1):
            m = fp128_square_sim(m)
            if m >= TWO_FP128:
                m = m >> 1  # Halve
                frac_top |= (1 << bit_pos)
        
        # f = m - ONE_FP128
        f_fp128 = fp128_sub(m, ONE_FP128)
        
        # Horner for h(f)
        result_fp128 = coeffs_fp128[DEGREE]
        for n in range(DEGREE - 1, -1, -1):
            result_fp128 = fp128_mul_sim(result_fp128, f_fp128)
            result_fp128 = fp128_add(result_fp128, coeffs_fp128[n])
        
        # log2(1+f) = f * INV_LN2 * h(f)
        temp = fp128_mul_sim(f_fp128, INV_LN2)
        poly_result = fp128_mul_sim(temp, result_fp128)
        
        # Total fractional part = frac_top + poly_result
        # (frac_top has bits in positions 127..121, poly_result has bits in positions 120..0)
        total_frac = fp128_add(frac_top, poly_result)
        
        # For x in [1, 2), int_part = 0, so result = total_frac
        log2_result = from_fp128(total_frac)
        log2_exact = mpmath.log(x_mpf) / mpmath.log(2)
        
        err = abs(log2_result - log2_exact)
        if err > worst_err:
            worst_err = err
            worst_x = x_mpf
    
    bits = float(-mpmath.log(worst_err, 2)) if worst_err > 0 else 999
    print(f"Tested {num_tests} points x in [1.001, 2)")
    print(f"Worst error: 2^-{bits:.1f} bits")
    print(f"Worst point: x = {float(worst_x):.10f}")
    print()
    
    if bits >= 120:
        print("SUCCESS: Full algorithm achieves 120+ bit precision")
    else:
        print(f"NOTE: Full algorithm precision is {bits:.1f} bits")

if __name__ == "__main__":
    main()
