#!/usr/bin/env python3
"""Generate contracts/src/ladder/LadderParams.sol from scripts/ladder/scenarios.json.

Every scenario parameter is floored once into each representation:
127.128 (int256), 64.64 (int128) and WAD 1e18 (int256), exactly, with
mpmath at 200 digits. Derived parameters (the amortisation payment) are
computed here so the contracts hold no arithmetic that is not a step.

    uv run scripts/ladder/gen_params.py          # write
    uv run scripts/ladder/gen_params.py --check  # fail if stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from mpmath import mp, mpf

mp.dps = 200
ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "scripts" / "ladder" / "scenarios.json"
OUT = ROOT / "contracts" / "src" / "ladder" / "LadderParams.sol"

SCALES = {"FP": mpf(2) ** 128, "ABDK": mpf(2) ** 64, "WAD": mpf(10) ** 18}


def value(expr: str):
    """Decimal literal or a/b of decimal literals."""
    if "/" in expr:
        a, b = expr.split("/")
        return mpf(a.strip()) / mpf(b.strip())
    return mpf(expr.strip())


def derived(params: dict, name: str):
    if name == "payment":
        P, r, n = params["principal"], params["rate"], params["term"]
        return P * r / (1 - (1 + r) ** (-n))
    raise KeyError(name)


def resolve(scn: dict) -> dict:
    p = {k: value(v) for k, v in scn.get("params", {}).items()}
    for k in scn.get("derived", {}):
        p[k] = derived(p, k)
    return p


def floor_scaled(x, scale) -> int:
    return int(mp.floor(x * scale))


def render(spec: dict) -> str:
    names: list[tuple[str, str, dict]] = []  # (CONST_NAME, "scenario.param", values)
    for scn in spec["scenarios"]:
        for k, v in resolve(scn).items():
            cname = (scn["id"] + "_" + k).upper().replace("-", "_")
            names.append((cname, f"{scn['id']}.{k}", {f: floor_scaled(v, s) for f, s in SCALES.items()}))
    lines = [
        "// SPDX-License-Identifier: MIT",
        "pragma solidity ^0.8.24;",
        "",
        "// GENERATED by scripts/ladder/gen_params.py from scripts/ladder/scenarios.json. Do not edit.",
        "",
        "/// @title LadderParams",
        "/// @notice Every scenario parameter floored once into each representation.",
        "///         Ids index the three accessor functions, so the scenario code is",
        "///         written once against ids and each adapter picks its own scale.",
        "library LadderParams {",
    ]
    for i, (cname, src, _) in enumerate(names):
        lines.append(f"    uint8 constant {cname} = {i}; // {src}")
    lines.append("")
    for form, typ in (("FP", "int256"), ("ABDK", "int128"), ("WAD", "int256")):
        fn = {"FP": "fp127", "ABDK": "abdk", "WAD": "wad"}[form]
        lines.append(f"    function {fn}(uint8 id) internal pure returns ({typ}) {{")
        for i, (cname, _, vals) in enumerate(names):
            lines.append(f"        if (id == {i}) return {vals[form]};")
        lines.append('        revert("param");')
        lines.append("    }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    text = render(json.loads(SPEC.read_text()))
    if "--check" in argv:
        if OUT.exists() and OUT.read_text() == text:
            print("gen-params ok")
            return 0
        print("LadderParams.sol is stale; run `make gen-params`")
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
