#!/usr/bin/env python3
"""Generate scripts/ladder/inputs.json from scripts/ladder/scenarios.json.

Every input's parameters are resolved exactly (mpmath at 200 digits; derived
values such as the amortisation payment computed here, so the contracts hold
no arithmetic that is not a step) and floored once into each representation:
127.128 (2^128), 64.64 (2^64) and WAD (1e18). The harness (test/ladder) and
the live verify button pass these integers to the adapters as calldata.

    uv run scripts/ladder/gen_inputs.py          # write
    uv run scripts/ladder/gen_inputs.py --check  # fail if stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from mpmath import mp, mpf

mp.dps = 200
ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "scripts" / "ladder" / "scenarios.json"
OUT = ROOT / "scripts" / "ladder" / "inputs.json"

# scale name -> (exponent form, integer scale, int range the adapter accepts)
SCALES = {
    "fp127": ("2**128", 2 ** 128, (-(2 ** 255), 2 ** 255 - 1)),
    "abdk": ("2**64", 2 ** 64, (-(2 ** 127), 2 ** 127 - 1)),
    "wad": ("10**18", 10 ** 18, (-(2 ** 255), 2 ** 255 - 1)),
}


def value(expr: str):
    """Decimal literal or a/b of decimal literals."""
    if "/" in expr:
        a, b = expr.split("/")
        return mpf(a.strip()) / mpf(b.strip())
    return mpf(expr.strip())


def derived(params: dict, name: str):
    if name == "payment":
        P, r, n = params["principal"], params["rate"], params["term"]
        return P * r / (1 - (1 + r) ** (-n))
    raise KeyError(name)


def resolve(params: dict, derived_names=()) -> dict:
    """Exact mpf values for a parameter set, derived values included."""
    p = {k: value(v) for k, v in params.items()}
    for k in derived_names:
        p[k] = derived(p, k)
    return p


def floor_scaled(x, scale: int) -> int:
    return int(mp.floor(x * scale))


def build(spec: dict) -> dict:
    cells = []
    for scn in spec["scenarios"]:
        for inp in scn["inputs"]:
            p = resolve(inp["params"], scn.get("derived", {}))
            cell = {"scenario": scn["index"], "id": scn["id"], "input": inp["name"], "order": scn["order"]}
            unrep = {}
            for name, (_, scale, (lo, hi)) in SCALES.items():
                ints = [floor_scaled(p[k], scale) for k in scn["order"]]
                cell[name] = [str(i) for i in ints]
                unrep[name] = any(i < lo or i > hi for i in ints)
            cell["unrepresentable"] = unrep
            cells.append(cell)
    return {
        "_doc": "Generated by scripts/ladder/gen_inputs.py from scenarios.json: every input's parameters floored into each representation, as decimal strings, in the scenario's `order`. unrepresentable marks a value outside the adapter's integer type; the adapter reverts ParamOutOfRange for it.",
        "ladder": spec["ladder"],
        "scales": {k: v[0] for k, v in SCALES.items()},
        "count": len(cells),
        "cells": cells,
    }


def main(argv: list[str]) -> int:
    text = json.dumps(build(json.loads(SPEC.read_text())), indent=1) + "\n"
    if "--check" in argv:
        if OUT.exists() and OUT.read_text() == text:
            print("gen-inputs ok")
            return 0
        print("inputs.json is stale; run `make gen-inputs`")
        return 1
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
