name: whalegames
static_sites:
  - name: whalegames-frontend
    github:
      branch: testnet
      deploy_on_push: true
    build_command: mkdir -p dist && cp index.html styles.css blockulator.png blockulator_favicon.png dist/ && cp -r js contracts dist/
    output_dir: dist
