name: whalegames

static_sites:
  - name: whalegames-frontend
    github:
      branch: testnet
      deploy_on_push: true
    
    # Build command to prepare static files
    build_command: npm run build
    
    # Output directory where build files are located
    output_dir: dist
    
    # Routes and error pages
    routes:
      - path: /
    error_document: index.html
    
    # Environment (client-side only)
    envs: []

