// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// GENERATED by scripts/ladder/gen_params.py from scripts/ladder/scenarios.json. Do not edit.

/// @title LadderParams
/// @notice Every scenario parameter floored once into each representation.
///         Ids index the three accessor functions, so the scenario code is
///         written once against ids and each adapter picks its own scale.
library LadderParams {
    uint8 constant COMPOUND_PRINCIPAL = 0; // compound.principal
    uint8 constant COMPOUND_RATE = 1; // compound.rate
    uint8 constant COMPOUND_POW_PRINCIPAL = 2; // compound-pow.principal
    uint8 constant COMPOUND_POW_RATE = 3; // compound-pow.rate
    uint8 constant BONDING_SQRT_SUPPLY = 4; // bonding-sqrt.supply
    uint8 constant BONDING_SQRT_UNIT = 5; // bonding-sqrt.unit
    uint8 constant ROUNDTRIP_X0 = 6; // roundtrip.x0
    uint8 constant AMORTISE_PRINCIPAL = 7; // amortise.principal
    uint8 constant AMORTISE_RATE = 8; // amortise.rate
    uint8 constant AMORTISE_TERM = 9; // amortise.term
    uint8 constant AMORTISE_PAYMENT = 10; // amortise.payment
    uint8 constant BLACK_SCHOLES_CHAIN_SPOT = 11; // black-scholes-chain.spot
    uint8 constant BLACK_SCHOLES_CHAIN_STRIKE = 12; // black-scholes-chain.strike
    uint8 constant BLACK_SCHOLES_CHAIN_SIGMA = 13; // black-scholes-chain.sigma
    uint8 constant BLACK_SCHOLES_CHAIN_T = 14; // black-scholes-chain.T
    uint8 constant BLACK_SCHOLES_CHAIN_R = 15; // black-scholes-chain.r
    uint8 constant BLACK_SCHOLES_CHAIN_TICK = 16; // black-scholes-chain.tick
    uint8 constant CUMULATIVE_PRODUCT_EPS = 17; // cumulative-product.eps
    uint8 constant COMPOUND_ANNUAL_PRINCIPAL = 18; // compound-annual.principal
    uint8 constant COMPOUND_ANNUAL_RATE = 19; // compound-annual.rate

    function fp127(uint8 id) internal pure returns (int256) {
        if (id == 0) return 3402823669209384634633746074317682114560000;
        if (id == 1) return 93228045731763962592705371899114578;
        if (id == 2) return 3402823669209384634633746074317682114560000;
        if (id == 3) return 93228045731763962592705371899114578;
        if (id == 4) return 340282366920938463463374607431768211456000;
        if (id == 5) return 340282366920938463463374607431768211456;
        if (id == 6) return 510423550381407695195061911147652317184;
        if (id == 7) return 102084710076281539039012382229530463436800000;
        if (id == 8) return 46614022865881981296352685949557289;
        if (id == 9) return 124543346293063477627595106320027165392896;
        if (id == 10) return 285989600704470405438025575687574625413684;
        if (id == 11) return 34028236692093846346337460743176821145600;
        if (id == 12) return 34028236692093846346337460743176821145600;
        if (id == 13) return 68056473384187692692674921486353642291;
        if (id == 14) return 170141183460469231731687303715884105728;
        if (id == 15) return 17014118346046923173168730371588410572;
        if (id == 16) return 3402823669209384634633746074317682114;
        if (id == 17) return 34028236692093846346337460743176821;
        if (id == 18) return 3402823669209384634633746074317682114560000;
        if (id == 19) return 34028236692093846346337460743176821145;
        revert("param");
    }

    function abdk(uint8 id) internal pure returns (int128) {
        if (id == 0) return 184467440737095516160000;
        if (id == 1) return 5053902485947822;
        if (id == 2) return 184467440737095516160000;
        if (id == 3) return 5053902485947822;
        if (id == 4) return 18446744073709551616000;
        if (id == 5) return 18446744073709551616;
        if (id == 6) return 27670116110564327424;
        if (id == 7) return 5534023222112865484800000;
        if (id == 8) return 2526951242973911;
        if (id == 9) return 6751508330977695891456;
        if (id == 10) return 15503527319602438145383;
        if (id == 11) return 1844674407370955161600;
        if (id == 12) return 1844674407370955161600;
        if (id == 13) return 3689348814741910323;
        if (id == 14) return 9223372036854775808;
        if (id == 15) return 922337203685477580;
        if (id == 16) return 184467440737095516;
        if (id == 17) return 1844674407370955;
        if (id == 18) return 184467440737095516160000;
        if (id == 19) return 1844674407370955161;
        revert("param");
    }

    function wad(uint8 id) internal pure returns (int256) {
        if (id == 0) return 10000000000000000000000;
        if (id == 1) return 273972602739726;
        if (id == 2) return 10000000000000000000000;
        if (id == 3) return 273972602739726;
        if (id == 4) return 1000000000000000000000;
        if (id == 5) return 1000000000000000000;
        if (id == 6) return 1500000000000000000;
        if (id == 7) return 300000000000000000000000;
        if (id == 8) return 136986301369863;
        if (id == 9) return 366000000000000000000;
        if (id == 10) return 840447900055066643507;
        if (id == 11) return 100000000000000000000;
        if (id == 12) return 100000000000000000000;
        if (id == 13) return 200000000000000000;
        if (id == 14) return 500000000000000000;
        if (id == 15) return 50000000000000000;
        if (id == 16) return 10000000000000000;
        if (id == 17) return 100000000000000;
        if (id == 18) return 10000000000000000000000;
        if (id == 19) return 100000000000000000;
        revert("param");
    }

}
