// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
// GENERATED by scripts/fp127/gen.py from FP127.yul.src. Do not edit.

/// @title FP127Lib
/// @notice Inlinable FP127: signed 127.128 fixed-point, one int256 per value,
///         value = raw / 2^128. Every function body is the same Yul that the
///         deployed FP127 object runs, so the two agree by construction.
/// @dev Blocks are memory-safe: the only memory touched is scratch space
///      (0x00..0x3f) for revert selectors.
library FP127Lib {
    error Overflow();
    error DivisionByZero();
    error OutOfRange();

    int256 internal constant ONE = int256(1) << 128;

    /// @notice Convert an 18-decimal fixed-point value to 127.128.
    /// @dev r = sdiv(x << 128, 1e18), rounding toward zero (matches Huff).
    ///      Reverts with OutOfRange if |x| >= 2^127, where the shift would
    ///      lose bits. The Huff silently wrapped here.
    function fromFixed18(int256 _x) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function fp127_fromFixed18(x) -> r {
                if iszero(eq(sar(127, x), sar(255, x))) { rev(0x7db3aba7) }
                r := sdiv(shl(128, x), 1000000000000000000)
            }

            _r := fp127_fromFixed18(_x)
        }
    }
    /// @notice Convert a 127.128 value to 18-decimal fixed-point.
    /// @dev r = floor(x * 1e18 / 2^128), rounding toward negative infinity
    ///      (matches Huff: signed high word times 1e18 plus the truncated
    ///      unsigned low word product). Cannot overflow for any int256 input.
    function toFixed18(int256 _x) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function fp127_toFixed18(x) -> r {
                let hi := sar(128, x)
                let lo := and(x, 0xffffffffffffffffffffffffffffffff)
                r := add(mul(hi, 1000000000000000000), shr(128, mul(lo, 1000000000000000000)))
            }

            _r := fp127_toFixed18(_x)
        }
    }
    /// @notice a + b. Reverts with Overflow on signed overflow.
    function add(int256 _a, int256 _b) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function fp127_add(a, b) -> r {
                r := add(a, b)
                if xor(slt(r, a), slt(b, 0)) { rev(0x35278d12) }
            }

            _r := fp127_add(_a, _b)
        }
    }
    /// @notice a - b. Reverts with Overflow on signed overflow.
    function sub(int256 _a, int256 _b) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function fp127_sub(a, b) -> r {
                r := sub(a, b)
                if xor(sgt(r, a), slt(b, 0)) { rev(0x35278d12) }
            }

            _r := fp127_sub(_a, _b)
        }
    }
    /// @notice floor(a * b / 2^128), the 127.128 product.
    /// @dev The full 512-bit signed product is formed as [p1:p0]. The unsigned
    ///      high word from mulmod is corrected to the signed high word by
    ///      subtracting b when a < 0 and a when b < 0. The result is the middle
    ///      256 bits of the 512-bit product, which is a floor toward negative
    ///      infinity, bit-identical to the Huff 4-term schoolbook on every
    ///      input where the Huff did not wrap. Reverts with Overflow when the
    ///      true result does not fit in int256; the Huff silently wrapped.
    function mul(int256 _a, int256 _b) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function fp127_mul(a, b) -> r {
                let p0 := mul(a, b)
                let mm := mulmod(a, b, not(0))
                let p1 := sub(sub(mm, p0), lt(mm, p0))
                p1 := sub(p1, mul(slt(a, 0), b))
                p1 := sub(p1, mul(slt(b, 0), a))
                if iszero(eq(sar(127, p1), sar(255, p1))) { rev(0x35278d12) }
                r := or(shl(128, p1), shr(128, p0))
            }

            _r := fp127_mul(_a, _b)
        }
    }
    /// @notice a / b in 127.128, truncated toward zero.
    /// @dev Signs are stripped, the unsigned quotient floor(|a| * 2^128 / |b|)
    ///      is formed with a 512-by-256 division, and the sign is restored. That
    ///      is truncation toward zero, matching the Huff. Reverts with
    ///      DivisionByZero when b == 0 (the Huff returned garbage) and with
    ///      Overflow when the quotient does not fit in int256 (the Huff wrapped).
    function div(int256 _a, int256 _b) internal pure returns (int256 _r) {
        assembly ("memory-safe") {
            function absw(x) -> r {
                let m := sar(255, x)
                r := sub(xor(x, m), m)
            }

            function divu(a, b) -> q {
                let prod0 := shl(128, a)
                let prod1 := shr(128, a)
                let remainder := mulmod(a, 0x100000000000000000000000000000000, b)
                prod1 := sub(prod1, gt(remainder, prod0))
                prod0 := sub(prod0, remainder)
                let twos := and(sub(0, b), b)
                b := div(b, twos)
                prod0 := div(prod0, twos)
                prod0 := or(prod0, mul(prod1, add(div(sub(0, twos), twos), 1)))
                let inv := xor(mul(3, b), 2)
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                q := mul(prod0, inv)
            }

            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function fp127_div(a, b) -> r {
                if iszero(b) { rev(0x23d359a3) }
                let neg := xor(slt(a, 0), slt(b, 0))
                let ua := absw(a)
                let ub := absw(b)
                if iszero(lt(shr(128, ua), ub)) { rev(0x35278d12) }
                let q := divu(ua, ub)
                if gt(q, add(0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff, neg)) { rev(0x35278d12) }
                r := sub(xor(q, sub(0, neg)), sub(0, neg))
            }

            _r := fp127_div(_a, _b)
        }
    }
}
