// GENERATED by scripts/fp127/gen.py from FP127.yul.src. Do not edit.
object "FP127" {
    code {
        datacopy(0, dataoffset("runtime"), datasize("runtime"))
        return(0, datasize("runtime"))
    }
    object "runtime" {
        code {
            switch shr(224, calldataload(0))
            case 0x43509138 { /* div(int256,int256) */
                ret(fp127_div(calldataload(4), calldataload(36)))
            }
            case 0x9aea0a13 { /* fromFixed18(int256) */
                ret(fp127_fromFixed18(calldataload(4)))
            }
            case 0xa2745c74 { /* toFixed18(int256) */
                ret(fp127_toFixed18(calldataload(4)))
            }
            case 0xa5f3c23b { /* add(int256,int256) */
                ret(fp127_add(calldataload(4), calldataload(36)))
            }
            case 0xadefc37b { /* sub(int256,int256) */
                ret(fp127_sub(calldataload(4), calldataload(36)))
            }
            case 0xbbe93d91 { /* mul(int256,int256) */
                ret(fp127_mul(calldataload(4), calldataload(36)))
            }
            default { revert(0, 0) }

            function ret(v) {
                mstore(0, v)
                return(0, 32)
            }

            function rev(sel) {
                mstore(0x00, shl(224, sel))
                revert(0x00, 0x04)
            }

            function absw(x) -> r {
                let m := sar(255, x)
                r := sub(xor(x, m), m)
            }

            function fp127_fromFixed18(x) -> r {
                if iszero(eq(sar(127, x), sar(255, x))) { rev(0x7db3aba7) }
                r := sdiv(shl(128, x), 1000000000000000000)
            }

            function fp127_toFixed18(x) -> r {
                let hi := sar(128, x)
                let lo := and(x, 0xffffffffffffffffffffffffffffffff)
                r := add(mul(hi, 1000000000000000000), shr(128, mul(lo, 1000000000000000000)))
            }

            function fp127_add(a, b) -> r {
                r := add(a, b)
                if xor(slt(r, a), slt(b, 0)) { rev(0x35278d12) }
            }

            function fp127_sub(a, b) -> r {
                r := sub(a, b)
                if xor(sgt(r, a), slt(b, 0)) { rev(0x35278d12) }
            }

            function fp127_mul(a, b) -> r {
                let p0 := mul(a, b)
                let mm := mulmod(a, b, not(0))
                let p1 := sub(sub(mm, p0), lt(mm, p0))
                p1 := sub(p1, mul(slt(a, 0), b))
                p1 := sub(p1, mul(slt(b, 0), a))
                if iszero(eq(sar(127, p1), sar(255, p1))) { rev(0x35278d12) }
                r := or(shl(128, p1), shr(128, p0))
            }

            function divu(a, b) -> q {
                let prod0 := shl(128, a)
                let prod1 := shr(128, a)
                let remainder := mulmod(a, 0x100000000000000000000000000000000, b)
                prod1 := sub(prod1, gt(remainder, prod0))
                prod0 := sub(prod0, remainder)
                let twos := and(sub(0, b), b)
                b := div(b, twos)
                prod0 := div(prod0, twos)
                prod0 := or(prod0, mul(prod1, add(div(sub(0, twos), twos), 1)))
                let inv := xor(mul(3, b), 2)
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                inv := mul(inv, sub(2, mul(b, inv)))
                q := mul(prod0, inv)
            }

            function fp127_div(a, b) -> r {
                if iszero(b) { rev(0x23d359a3) }
                let neg := xor(slt(a, 0), slt(b, 0))
                let ua := absw(a)
                let ub := absw(b)
                if iszero(lt(shr(128, ua), ub)) { rev(0x35278d12) }
                let q := divu(ua, ub)
                if gt(q, add(0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff, neg)) { rev(0x35278d12) }
                r := sub(xor(q, sub(0, neg)), sub(0, neg))
            }
        }
    }
}
