// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;
// GENERATED by scripts/fp127/gen.py from FP127.yul.src. Do not edit.

/// @title IFP127
/// @notice Interface of the deployed FP127 object. Values are signed 127.128
///         fixed-point: one int256 whose value is raw / 2^128.
interface IFP127 {
    error Overflow();
    error DivisionByZero();
    error OutOfRange();

    /// @notice Convert an 18-decimal fixed-point value to 127.128.
    /// @dev r = sdiv(x << 128, 1e18), rounding toward zero (matches Huff).
    ///      Reverts with OutOfRange if |x| >= 2^127, where the shift would
    ///      lose bits. The Huff silently wrapped here.
    function fromFixed18(int256 x) external pure returns (int256 r);
    /// @notice Convert a 127.128 value to 18-decimal fixed-point.
    /// @dev r = floor(x * 1e18 / 2^128), rounding toward negative infinity
    ///      (matches Huff: signed high word times 1e18 plus the truncated
    ///      unsigned low word product). Cannot overflow for any int256 input.
    function toFixed18(int256 x) external pure returns (int256 r);
    /// @notice a + b. Reverts with Overflow on signed overflow.
    function add(int256 a, int256 b) external pure returns (int256 r);
    /// @notice a - b. Reverts with Overflow on signed overflow.
    function sub(int256 a, int256 b) external pure returns (int256 r);
    /// @notice floor(a * b / 2^128), the 127.128 product.
    /// @dev The full 512-bit signed product is formed as [p1:p0]. The unsigned
    ///      high word from mulmod is corrected to the signed high word by
    ///      subtracting b when a < 0 and a when b < 0. The result is the middle
    ///      256 bits of the 512-bit product, which is a floor toward negative
    ///      infinity, bit-identical to the Huff 4-term schoolbook on every
    ///      input where the Huff did not wrap. Reverts with Overflow when the
    ///      true result does not fit in int256; the Huff silently wrapped.
    function mul(int256 a, int256 b) external pure returns (int256 r);
    /// @notice a / b in 127.128, truncated toward zero.
    /// @dev Signs are stripped, the unsigned quotient floor(|a| * 2^128 / |b|)
    ///      is formed with a 512-by-256 division, and the sign is restored. That
    ///      is truncation toward zero, matching the Huff. Reverts with
    ///      DivisionByZero when b == 0 (the Huff returned garbage) and with
    ///      Overflow when the quotient does not fit in int256 (the Huff wrapped).
    function div(int256 a, int256 b) external pure returns (int256 r);
}
