#!/usr/bin/env python3
"""docs/benchmarks/pi.md from test/fp127/PiCompare.t.sol:

    forge test --match-contract PiCompare -vv | uv run scripts/fp127/pi_compare.py
"""
from __future__ import annotations
import sys
from pathlib import Path
from mpmath import mp, mpf, pi, nstr, floor, log10

mp.dps = 60
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "benchmarks" / "pi.md"
LABEL = {"fp127lib": "FP127Lib primitives", "fp127-pi": "FP127 `pi(terms)`", "solady": "Solady", "prb": "PRBMath SD59x18", "abdk": "ABDKMath64x64", "prb-constant": "PRBMath `PI` constant"}


def scale_of(s: str) -> int:
    b, e = s.split("**")
    return int(b) ** int(e)


def main() -> int:
    rows = []
    for line in sys.stdin:
        if "PICMP|" not in line:
            continue
        _, form, terms, raw, scale, gas = line[line.index("PICMP|"):].strip().split("|")
        v = mpf(int(raw)) / scale_of(scale)
        e = abs(v - pi) / pi
        d = int(floor(-log10(e))) if e > 0 else 60
        rows.append((form, int(terms), nstr(v, 40), d, int(gas)))
    forms = ["fp127-pi", "fp127lib", "abdk", "solady", "prb"]
    L = ["# Pi by Ramanujan's series, through each library's primitives", "",
         "The same recipe, 1/pi = (2 sqrt2 / 9801) sum (4k)! (1103 + 26390 k) / ((k!)^4 396^(4k)), evaluated with each library's own sqrt, mul and div on its own grid (test/fp127/PiCompare.t.sol). The integer term ratios are exact in every format; what differs is the grid the running term lives on, the sqrt(2), and the final reciprocal. Correct digits are against pi; gas is the inline call. Generated by `make pi-compare`.", "",
         "| terms | " + " | ".join(LABEL[f] for f in forms) + " |", "|---:|" + "---:|" * len(forms)]
    by = {(f, t): (v, d, g) for f, t, v, d, g in rows}
    for t in range(1, 7):
        cells = []
        for f in forms:
            v, d, g = by[(f, t)]
            cells.append(f"{d} ({g:,})")
        L.append(f"| {t} | " + " | ".join(cells) + " |")
    c = by[("prb-constant", 0)]
    L += ["", f"PRBMath's `PI` constant, for reference: {c[0][:22]}…, {c[1]} digits, the most an 18-decimal grid can hold. "
          f"At five terms FP127's `pi` returns {by[('fp127-pi', 5)][0]}…, {by[('fp127-pi', 5)][1]} digits; truth {nstr(pi, 40)}…", ""]
    L += ["Values at five terms:", "", "| library | value |", "|---|---|"]
    for f in forms:
        L.append(f"| {LABEL[f]} | `{by[(f, 5)][0]}` |")
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    for t in (1, 5):
        print("terms", t, {f: by[(f, t)][1] for f in forms})
    return 0


if __name__ == "__main__":
    sys.exit(main())
