#!/usr/bin/env python3
"""Render docs/fp127/precision.md from docs/fp127/precision.json, which
test/fp127/Precision.t.sol writes on every run."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "docs" / "fp127" / "precision.json"
OUT = ROOT / "docs" / "fp127" / "precision.md"

ORDER = [
    "add", "sub", "mul", "div", "fromFixed18", "toFixed18",
    "exp", "exp2", "exp10", "ln", "log2", "log10", "log2Up",
    "sqrt", "cbrt", "pow", "inv", "abs", "neg", "sign", "min", "max", "clamp", "avg",
    "zeroFloorSub", "dist", "lerp", "floor", "ceil", "frac", "round", "gcd", "factorial",
    "hypot", "gavg", "lambertW0", "lambertWm1",
]


def fmt_bits(b: int) -> str:
    return "exact" if b >= 255 else str(b)


def main() -> int:
    data = json.loads(SRC.read_text())
    lines = [
        "# FP127 precision",
        "",
        "Generated by `make test` (test/fp127/Precision.t.sol) against mpmath at 200 decimal "
        "places (scripts/fp127/oracle.py), over the committed vectors in test/fp127/vectors/. "
        "Regenerate the table with `make precision-report`.",
        "",
        "Bits are relative correct bits of the 127.128 result: msb(|truth|) - msb(|truth - got|). "
        "\"exact\" means bit-identical, or within 2 ULP for an approximated op. "
        "`reverts` counts vectors where the oracle and the Yul both reject the input with the same error.",
        "",
        "| op | vectors | reverts | min bits | mean bits | worst input |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for op in ORDER:
        e = data.get(op)
        if not e:
            continue
        worst = e.get("worstInput", "") or ""
        if worst:
            worst = "`" + worst.replace(",", "`, `") + "`"
        lines.append(f"| {op} | {e['n']} | {e.get('reverts', 0)} | {fmt_bits(int(e['minBits']))} | {fmt_bits(int(e['meanBits']))} | {worst} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
